@startuml
title 基于GitHub的实验管理平台--用例图
actor 老师
actor 学生
actor 用户
用户 <|-- 老师
用户 <|-- 学生

package 用户用例集 {
用户 --up-> (登入)
用户 --up-> (登出)
用户 --up-> (查看个人信息)
用户 --up-> (修改个人信息)

}
package 业务用例集 {
老师 ---> (批改作业)
老师 ---> (公告)
老师 ---> (查看学生信息)
老师 ---> (学生列表)
老师 ---> (查看成绩)
学生 ---> (学生列表)
学生 ---> (查看成绩)
学生 ---> (公告)
学生 ---> (选择课程/学期)
}

@enduml